name: doan_cuahangbansach
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  animated_bottom_navigation_bar: ^1.0.1
  animated_notch_bottom_bar: ^1.0.0
  intl_phone_number_input: ^0.7.4
  carousel_slider: ^4.2.1
  mongo_dart: ^0.10.3  
  image_picker: ^1.1.2
  timeline_tile: ^2.0.0
  assets: ^0.0.1
  iconsax: ^0.0.8
  rating_bar_flutter: ^1.0.2
  flutter_rating_bar: ^4.0.1
  iconsax_flutter: ^1.0.0
  iconsax_plus: ^1.0.0
  float_column: ^2.1.6
  http: ^1.2.1
  shared_preferences: ^2.0.13  
  another_flushbar: ^1.12.30
  fluttertoast: ^8.2.6
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  shared_preferences: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/products/
    - assets/carosel/
    - assets/category/
    - assets/images/
    - assets/icons/
    - assets/images/membership/
    - assets/images/item/

